project:
  type: book
  output-dir: docs  
book:
  title: "DSA 202: Introduction to Data Visualisation"
  author: "Tom R. Leppard"
  date: "6/10/2025"
  sidebar:
      search: true
      title: " "
      logo: cover.png
  cover-image: cover.png
  cover-image-alt: |
    A textbook cover with a bird. 
   
  chapters:
    - index.qmd
    - part: "Unit 1: Working with Data"
      chapters: 
      - Data Types and Structures.qmd
      - Summarising Data.qmd
    - part: "Unit 2: Visualising Data"
      chapters: 
      - Categorical Data.qmd
      - Line Graphs.qmd
      - Scatterplots.qmd
      - Beyond Static Visualisation.qmd
      - Cleaning and Annotating.qmd
      - Accessibility and Ethics.qmd
    - part: "Unit 3: Alternative Data Types"
      chapters: 
      - Networks.qmd
      - Text.qmd
      - Sankey.qmd
    - part: "Assignments"
      chapters:
      - Assignment 1
      - Assignment 2
      - Assignment 3
      - Assignment 4
      - Final Project.qmd
      

bibliography: references.bib

format:
  html:
    theme:
      - simplex
      - brand
  
  pdf:
    documentclass: scrreprt

editor: visual